module.exports = [
  {
    name: "local",
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "admin",
    password: "housingcloudpassword",
    database: "housing-cloud",
    entities: ["src/entity/*.ts"],
    migrationsTableName: "migrations",
    migrations: ["migration/*.ts"],
    cli: {
      migrationsDir: "migration",
    },
    logging: "error",
    synchronize: false,
  },
  {
    name: "test",
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "admin",
    password: "password",
    database: "housing-cloud-test",
    entities: ["src/entity/*.ts"],
    logging: "error",
    synchronize: true,
  },
  {
    name: "development",
    type: "postgres",
    host: process.env.DEVELOPMENT_TYPEORM_HOST,
    port: process.env.DEVELOPMENT_TYPEORM_PORT,
    username: process.env.DEVELOPMENT_TYPEORM_USER,
    password: process.env.DEVELOPMENT_TYPEORM_PASSWORD,
    database: process.env.DEVELOPMENT_TYPEORM_DATABASE,
    entities: ["build/entity/*.js"],
    logging: "error",
    synchronize: true,
  },
  {
    name: "staging",
    type: "postgres",
    host: process.env.STAGING_TYPEORM_HOST,
    port: process.env.STAGING_TYPEORM_PORT,
    username: process.env.STAGING_TYPEORM_USER,
    password: process.env.STAGING_TYPEORM_PASSWORD,
    database: process.env.STAGING_TYPEORM_DATABASE,
    entities: ["build/entity/*.js"],
    logging: "error",
    synchronize: true,
  },
  {
    name: "production",
    type: "postgres",
    host: process.env.PRODUCTION_TYPEORM_HOST,
    port: process.env.PRODUCTION_TYPEORM_PORT,
    username: process.env.PRODUCTION_TYPEORM_USER,
    password: process.env.PRODUCTION_TYPEORM_PASSWORD,
    database: process.env.PRODUCTION_TYPEORM_DATABASE,
    entities: ["build/entity/*.js"],
    logging: "error",
    synchronize: true,
  },
];
